ui: mocha-bdd
html: ./test/fixture.html
browsers:
  - name: chrome
    version: 41..latest
  - name: firefox
    version: 35..latest
  - name: safari
    version: latest
  - name: ie
    version: 9..latest
  - name: iphone
    version: 6..latest
  - name: android
    version: 4..latest
